name: Build
permissions:
  contents: write

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build executable 🔨
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pipx install poetry

      - run: pipx inject poetry poetry-dynamic-versioning

      - run: poetry env use python3.12

      - run: poetry install

      - run: poetry run python -m portable

      - name: Get name of the portable build
        id: get_name
        shell: bash
        run: echo "BUILD_NAME=$(ls dist | grep smpmgr-.*\.zip)" >> $GITHUB_OUTPUT

      - name: Upload artifact 📦
        uses: actions/upload-artifact@v4
        with:
          path: dist/${{ steps.get_name.outputs.BUILD_NAME }}
          name: ${{ steps.get_name.outputs.BUILD_NAME }}

      - name: Upload portable build 🚀
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ steps.get_name.outputs.BUILD_NAME }}
          tag: ${{ github.ref }}
